# Generated by Django 3.2.2 on 2021-05-26 21:41

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media_Type_Dim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Type_Dim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_location_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_media.location_fact')),
                ('project_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_media.project_type_dim')),
            ],
        ),
        migrations.CreateModel(
            name='Media_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('path', models.TextField()),
                ('label', models.CharField(help_text='The name of the tag, without ancestors', max_length=255)),
                ('level', models.IntegerField(default=1, help_text='The level of the tag in the tree')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='add_media.media_tags')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug', 'parent')},
            },
            bases=(tagulous.models.models.BaseTagTreeModel, models.Model),
        ),
        migrations.CreateModel(
            name='Media_Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extension_filtered', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=20)),
                ('proxy_file_name', models.CharField(max_length=200)),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('fps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('frame_count', models.IntegerField(null=True)),
                ('duration_sec', models.IntegerField(null=True)),
                ('bitrate', models.IntegerField(null=True)),
                ('channels', models.IntegerField(null=True)),
                ('sample_rate_hz', models.IntegerField(null=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('media_location_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_location', to='add_media.location_fact')),
                ('media_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_media.media_type_dim')),
                ('project_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_media.project_fact')),
                ('proxy_location_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_location', to='add_media.location_fact')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='This field splits on commas', space_delimiter=False, to='add_media.Media_Tags', tree=True)),
            ],
        ),
    ]
