# Generated by Django 3.2.2 on 2021-05-27 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media_fact',
            old_name='media_type_fk',
            new_name='file_type_fk',
        ),
        migrations.RemoveField(
            model_name='media_fact',
            name='media_location_fk',
        ),
        migrations.RemoveField(
            model_name='media_fact',
            name='proxy_location_fk',
        ),
        migrations.AddField(
            model_name='media_fact',
            name='file_location_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_location', to='add_media.location_fact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media_fact',
            name='proxy_file_location_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='proxy_file_location', to='add_media.location_fact'),
            preserve_default=False,
        ),
    ]
