# Generated by Django 3.2.2 on 2021-06-04 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_media', '0002_auto_20210527_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_fact',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media_fact',
            name='datetime_added',
            field=models.DateTimeField(blank=True),
        ),
    ]
