# Generated by Django 3.2.2 on 2021-06-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_media', '0003_auto_20210604_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_fact',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='media_fact',
            name='datetime_created',
            field=models.DateTimeField(blank=True),
        ),
    ]
